src/Entity/Answer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnswerRepository")
 */
class Answer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Proposition;

    /**
     * @ORM\Column(type="integer")
     */
    private $Score;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question", inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProposition(): ?string
    {
        return $this->Proposition;
    }

    public function setProposition(string $Proposition): self
    {
        $this->Proposition = $Proposition;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->Score;
    }

    public function setScore(int $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->Question;
    }

    public function setQuestion(?Question $Question): self
    {
        $this->Question = $Question;

        return $this;
    }
}

templates/anon.html.twig
<div class="navbar-nav mr-auto">
    {#<a href="{{ path('app_login') }}" class="btn btn-outline-light mx-1">{{ 'login'|trans }}</a>
    <a href="{{ path('app_register') }}" class="btn btn-outline-light mx-1">{{'register'|trans}}</a>#}
</div>

templates/anon_body.html.twig
{#
{% set url = path(app.request.attributes.get('_route'),
    app.request.attributes.get('_route_params')) %}
{{ url }}
#}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-75" src="https://loremflickr.com/640/360" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://loremflickr.com/640/360" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://loremflickr.com/640/360" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/css-rpg-quizz.css') }}">
	</head>
    <body>
    <a href="{{ path('pages') }}" class="btn btn-success">Home</a>
    <a href="{{ path('pages') }}" class="btn btn-outline-info">A propos</a>
    <a href="{{ path('pages') }}" class="btn btn-outline-info">Règles</a>
    <a href="{{ path('pages') }}" class="btn btn-outline-info">CGU</a>
    <a href="{{ path('pages') }}" class="btn btn-outline-info">Mentions Légales</a>
    <br>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/logged.html.twig
<ul class="navbar-nav  mr-auto">
    <li class="nav-item">
{#
        <a href="{{ path('app_account') }}" class="nav-link">
#}
            <span class="">Compte</span>
        </a>
    </li>
    {% if app.user.persona is not empty %}
        <li class="nav-item">
            {#<a href="{{ path('persona_show', {'id': app.user.persona.id}) }}" class="nav-link"> #}{# à changer dans le controller, parce que voilà #}{#
                <span class="">Personnage</span>
            </a>#}
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Scores</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Score personnel</a>
                <a class="dropdown-item" href="#">Leaderboard</a>
            </div>
        </li>
    {% endif %}

</ul>
<span class="text-light mr-auto">
        {#{{ 'hello'|trans }} {{ app.user.username|capitalize }},&nbsp;
        {% if app.user.persona is not empty %}
            votre personnage est {{ "level"|trans }} {{ app.user.persona.level }}
        {% endif %}#}
    </span>
<div id="deuxieme_partie_menu" class="my-2 my-lg-0">
{#
    <a href="{{ path('app_logout') }}" class="btn btn-outline-light mx-1">{{ 'logout'|trans }}</a>
#}
</div>

templates/menu.html.twig
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div id="premier_partie_menu">
                        {% if app.user is not empty %}
                            <a class="navbar-brand" href="#">
                                    <img src="{{ app.user.avatar }}" class="image_menu rounded-pill" alt="">
                            </a>
                        {% endif %}
			<a class="navbar-brand" href="#">Bonjour {{ app.user.username }} </a>
                        {% if app.user is not empty %}
                            <a class="navbar-brand" href="#">( Score {{ app.user.score }} )</a>
                        {% endif %}
		</div>
		<div id="deuxieme_partie_menu" class="my-2 my-lg-0">
			<a href="{{ path('app_logout') }}" class="btn btn-light">Deconnexion</a>
		</div>
	</nav
</div>